### ISSUE TITLE
[TODO] Home Assistant Integration checklist

### ISSUE THREAD

**Issue by LarsK1** [LarsK1/hass_solvis_control#78]
Hi everyone,
HomeAssistant recently published new criteria for Integration - therefore the next goal will be to score as high as possible :)

## Bronze
- [X] `config-flow` - Integration needs to be able to be set up via the UI
    - [X] Uses `data_description` to give context to fields (see #160 )
    - [X] Uses `ConfigEntry.data` and `ConfigEntry.options` correctly (see #160 )
- [X] `test-before-configure` - Test a connection in the config flow
- [X] `unique-config-entry` - Don't allow the same device or service to be able to be set up twice
- [X] `config-flow-test-coverage` - Full test coverage for the config flow (Thanks @fkhr79  )
- [X] `runtime-data` - Use ConfigEntry.runtime_data to store runtime data (See #160 )
- [X] `test-before-setup` - Check during integration initialization if we are able to set it up correctly
- [X] `appropriate-polling` - If it's a polling integration, set an appropriate polling interval
- [X] `entity-unique-id` - Entities have a unique ID (https://github.com/LarsK1/hass_solvis_control/commit/b88d0fbb5badbbca69e8946aed380e56665c12ab)
- [X] `has-entity-name` - Entities use has_entity_name = True
- [X] `entity-event-setup` - Entities event setup
- [X] `dependency-transparency` - Dependency transparency
- [X] `action-setup` - Service actions are registered in async_setup (Not applicable for V2.0.0)
- [X] `common-modules` - Place common patterns in common modules (See #159, Thanks @fkhr79 )
- [x] `docs-high-level-description` - The documentation includes a high-level description of the integration brand, product, or service (Thanks @timmost, @fkhr79 )
- [x] `docs-installation-instructions` - The documentation provides step-by-step installation instructions for the integration, including, if needed, prerequisites (Thanks @timmost )
- [X] `docs-removal-instructions` - The documentation provides removal instructions (Thanks @fkhr79 )
- [X] `docs-actions` - The documentation describes the provided service actions that can be used (Not applicable, since no service action are available as of now)
- [X] `brands` - Has branding assets available for the integration

## Silver
- [X] `config-entry-unloading` - Support config entry unloading
- [X] `log-when-unavailable` - If internet/device/service is unavailable, log once when unavailable and once when back connected
- [X] `entity-unavailable` - Mark entity unavailable if appropriate
- [X] `action-exceptions` - Service actions raise exceptions when encountering failures (not applicable for V2.0.0, since no service actions are available as of now)
- [X] `reauthentication-flow` - Reauthentication flow (Not applicable, since no auth is necessary)
- [X] `parallel-updates` - Set Parallel updates
- [X] `test-coverage` - Above 95% test coverage for all integration modules (See #158 )
- [X] `integration-owner` - Has an integration owner
- [X] `docs-installation-parameters` - The documentation describes all integration installation parameters (Thanks @fkhr79 )
- [X] `docs-configuration-parameters` - The documentation describes all integration configuration options (Thanks @fkhr79 )

## Gold
- [X] `entity-translations` - Entities have translated names
- [X] `entity-device-class` - Entities use device classes where possible
- [X] `devices` - The integration creates devices
- [X] `entity-category` - Entities are assigned an appropriate EntityCategory
- [X] `entity-disabled-by-default` - Integration disables less popular (or noisy) entities
- [X] `discovery` - Can be discovered (See #161 )
- [X] `stale-devices` - Clean up stale devices
- [X] `diagnostics` - Implements diagnostics (https://github.com/LarsK1/hass_solvis_control/commit/7053c4cae5738cdd82a79b184e30dd231bde8b7d)
- [X] `exception-translations` - Exception messages are translatable
- [X] `icon-translations` - Icon translations
- [X] `reconfiguration-flow` - Integrations should have a reconfigure flow
- [X] `dynamic-devices` - Devices added after integration setup (See #161)
- [X] `discovery-update-info` - Integration uses discovery info to update network information (See #161)
- [ ] `repair-issues` - Repair issues and repair flows are used when user intervention is needed
- [ ] `docs-use-cases` - The documentation describes use cases to illustrate how this integration can be used (See #162 )
- [X] `docs-supported-devices` - The documentation describes known supported / unsupported devices (Thanks @fkhr79 )
- [ ] `docs-supported-functions` - The documentation describes the supported functionality, including entities, and platforms (See #162 )
- [X] `docs-data-update` - The documentation describes how data is updated (Thanks @fkhr79 )
- [X] `docs-known-limitations` - The documentation describes known limitations of the integration (not to be confused with bugs)
- [X] `docs-troubleshooting` - The documentation provides troubleshooting information (Thanks @fkhr79 )
- [ ] `docs-examples` - The documentation provides automation examples the user can use. (See #162 )

## Platinum
- [X] `async-dependency` - Dependency is async
- [ ] `inject-websession` - The integration dependency supports passing in a websession (Not planned for V2.0.0)
- [ ] `strict-typing` - Strict typing (Not planned for V2.0.0)

**Comment by timmost** [comment]
Hi @LarsK1 , wie kann man helfen?
VG timmo

**Comment by LarsK1** [comment]
Hi @timmost ,
Du könntest super bei den Themen mit docs-* helfen. Am einfachsten klonst Du Dir das Repo und bearbeitest die README.md.

**Comment by timmost** [comment]
(Working in my fork)
done:
- docs-high-level-description - The documentation includes a high-level description of the integration brand, product, or service

**Comment by fkhr79** [comment]
I was curious what's meant with these criteria and had a look at the dev pages: the checklist on [the developers page](https://developers.home-assistant.io/docs/core/integration-quality-scale/checklist) looks different...?!

**Comment by LarsK1** [comment]
@fkhr79 seems to have changed in order, but not regarding it's content...
